resources:
  - name: docker-learning
    type: git
    icon: github
    source:
      uri: https://github.com/I-AM-NULL/DockerLearning

jobs:
  - name: build-and-deploy
    plan:
      - get: DockerLearning
      - task: build-and-deploy
        file: DockerLearning/build-and-deploy.yml